sudo: required
services:
  - docker

before_install:
  - docker image build -t crileroro/react-test-client -f ./client/Dockerfile.dev ./client

script:
  - docker container run -e CI=true crileroro/react-test-client npm run test -- --coverage

after_success:
  - docker image build -t crileroro/react-prd-client ./client
  - docker image build -t crileroro/react-prd-nginx ./nginx
  - docker image build -t crileroro/react-prd-server ./server
  - docker image build -t crileroro/react-prd-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push crileroro/react-prd-client
  - docker push crileroro/react-prd-nginx 
  - docker push crileroro/react-prd-server
  - docker push crileroro/react-prd-worker




deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-522410467679"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY